linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocyclo
    - gosec

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G204 # Subprocess launched with variable

service:
  golangci-lint-version: latest

# The latest supported version
version: "1.0.0" 